<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<!DOCTYPE html>

<html>
  <head>
    <title>Assignments</title>
    <%-- Set the base path to the path where the war is deployed, --%>
    <%-- e.g., /assignment. --%>
    <base href="${pageContext.request.contextPath}/" />
    <%-- Use config.jsp to create a JS object for the configs. --%>
    <jsp:include page="config.jsp" />
    <%-- Use the JSP generated by Angular CLI to reference all the --%>
    <%-- necessary styles and scripts. --%>
    <jsp:include page="/webjars/client/includes.jsp" />
    <link rel="icon" type="image/x-icon" href="webjars/client/favicon.ico">
  </head>
  <body>
    <planvas-root></planvas-root>
  </body>
</html>
